"""Paper-portfolio dashboard (P-B) — a single stable GitHub Pages page.

Unlike the per-signal reports (non-guessable filenames, owner positions never
shown), the paper portfolio is VIRTUAL and publishable, so it lives at a fixed
URL the owner can bookmark: {PAGES_BASE_URL}/paper.html. The page is fully
self-contained (inline CSS + inline SVG equity line — no external deps) and is
regenerated by the weekly job from paper/trades.parquet + open positions.

It IS the human-readable journal (recent decisions + rationale); the
machine-readable record for backtesting/Claude stays trades.parquet (P-C).
"""

import html
import logging
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pandas as pd

from config import settings
from src.paper import stats
from src.report.html_builder import REPORTS_OUT_DIR

logger = logging.getLogger(__name__)

KST = timezone(timedelta(hours=9))
PAPER_REPORT_NAME = "paper.html"


def _fmt_pct(value: float | None, signed: bool = True) -> str:
    if value is None or value != value:
        return "—"
    return f"{value:+.1f}%" if signed else f"{value:.1f}%"


def _color(value: float | None) -> str:
    if value is None or value != value:
        return "#555"
    return "#c0392b" if value < 0 else "#1e7e34"  # red down / green up (KR convention)


def _sparkline(values: list[float], width: int = 640, height: int = 140) -> str:
    """Inline SVG equity line (no JS, no CDN). Empty string if too few points."""
    if len(values) < 2:
        return ""
    lo, hi = min(values), max(values)
    span = (hi - lo) or 1.0
    pad = 8
    step = (width - 2 * pad) / (len(values) - 1)
    pts = [
        (pad + i * step, height - pad - (v - lo) / span * (height - 2 * pad))
        for i, v in enumerate(values)
    ]
    line = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
    last_up = values[-1] >= values[0]
    stroke = "#1e7e34" if last_up else "#c0392b"
    return (
        f'<svg viewBox="0 0 {width} {height}" width="100%" height="{height}" '
        f'preserveAspectRatio="none" role="img" aria-label="자산 곡선">'
        f'<polyline fill="none" stroke="{stroke}" stroke-width="2" points="{line}"/>'
        f"</svg>"
    )


def _stat_card(label: str, value: str, color: str = "#222") -> str:
    return (
        f'<div class="card"><div class="lbl">{html.escape(label)}</div>'
        f'<div class="val" style="color:{color}">{html.escape(value)}</div></div>'
    )


def _trade_rows(trades: pd.DataFrame, limit: int = 20) -> str:
    if trades is None or trades.empty:
        return '<tr><td colspan="7">아직 청산된 가상 거래가 없습니다.</td></tr>'
    df = trades.copy()
    df["exit_date"] = pd.to_datetime(df["exit_date"], errors="coerce")
    df = df.sort_values("exit_date", ascending=False).head(limit)
    out = []
    for _, r in df.iterrows():
        ret = float(r["return_pct"]) if pd.notna(r["return_pct"]) else float("nan")
        out.append(
            "<tr>"
            f"<td>{html.escape(str(r['ticker']))}</td>"
            f"<td>{html.escape(str(r.get('grade') or '—'))}</td>"
            f"<td>{html.escape(str(r['entry_date']))} → {html.escape(str(r['exit_date'].date()))}</td>"
            f"<td>{int(r['holding_days']) if pd.notna(r['holding_days']) else '—'}일</td>"
            f'<td style="color:{_color(ret)}">{_fmt_pct(ret)}</td>'
            f"<td>{html.escape(str(r.get('exit_reason') or '—'))}</td>"
            f"<td class='why'>{html.escape(str(r.get('rationale_kr') or ''))}</td>"
            "</tr>"
        )
    return "\n".join(out)


def _open_rows(open_rows: list[dict]) -> str:
    if not open_rows:
        return '<tr><td colspan="5">현재 보유 중인 가상 포지션이 없습니다.</td></tr>'
    out = []
    for o in open_rows:
        up = float(o.get("unrealized_pct") or 0.0)
        out.append(
            "<tr>"
            f"<td>{html.escape(str(o.get('ticker')))}</td>"
            f"<td>{html.escape(str(o.get('grade') or '—'))}</td>"
            f"<td>{html.escape(str(o.get('entry_date')))}</td>"
            f"<td>{o.get('entry_price')} → {o.get('last_close')}</td>"
            f'<td style="color:{_color(up)}">{_fmt_pct(up)}</td>'
            "</tr>"
        )
    return "\n".join(out)


def _breakdown_rows(rows: list[dict]) -> str:
    if not rows:
        return '<tr><td colspan="3">—</td></tr>'
    out = []
    for r in rows:
        wr = r["win_rate"] * 100 if r["win_rate"] == r["win_rate"] else float("nan")
        out.append(
            f"<tr><td>{html.escape(r['key'])}</td><td>{r['n']}건</td>"
            f"<td>승률 {_fmt_pct(wr, signed=False) if wr == wr else '—'} · 평균 "
            f"<span style='color:{_color(r['avg_return'])}'>{_fmt_pct(r['avg_return'])}</span></td></tr>"
        )
    return "\n".join(out)


def build_paper_report(
    trades: pd.DataFrame,
    open_rows: list[dict] | None = None,
    *,
    benchmark_pct: float | None = None,
    out_dir: Path | None = None,
) -> Path:
    """Render the paper-portfolio dashboard to a stable paper.html.

    Returns:
        Path to the written file (REPORTS_OUT_DIR/paper.html by default).
    """
    open_rows = open_rows or []
    out_dir = out_dir or REPORTS_OUT_DIR
    s = stats.summarize(trades, open_rows)
    curve = stats.equity_curve(trades)
    equity_pts = [s["start_equity"]] + curve["equity"].tolist() if not curve.empty else []
    spark = _sparkline(equity_pts)

    period = (
        f"{s['period_start']} ~ {s['period_end']}"
        if s["period_start"] and s["period_end"]
        else "거래 없음"
    )
    bench_html = ""
    if benchmark_pct is not None:
        excess = s["total_return_pct"] - benchmark_pct
        bench_html = _stat_card("vs S&P500 (동기간)", f"{benchmark_pct:+.1f}% / 초과 {excess:+.1f}%p", _color(excess))

    cards = "".join(
        [
            _stat_card("총 수익률", _fmt_pct(s["total_return_pct"]), _color(s["total_return_pct"])),
            _stat_card("현재 자산", f"{s['current_equity']:,.0f}", "#222"),
            _stat_card("청산 / 보유", f"{s['n_closed']}건 / {s['n_open']}개", "#222"),
            _stat_card(
                "승률 · PF",
                f"{s['win_rate'] * 100:.0f}% · {stats._pf_str(s['profit_factor'])}"
                if s["n_closed"]
                else "—",
                "#222",
            ),
            _stat_card("최대낙폭(MDD)", _fmt_pct(s["max_drawdown_pct"]), _color(s["max_drawdown_pct"])),
            bench_html,
        ]
    )

    generated = datetime.now(KST).strftime("%Y-%m-%d %H:%M KST")
    cost_note = f"슬리피지 {settings.PAPER_SLIPPAGE_BPS:.0f}bps + 수수료 {settings.PAPER_FEE_BPS:.0f}bps 가정"
    html_doc = f"""<!doctype html>
<html lang="ko"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>가상 포트폴리오 — swing-trader</title>
<style>
 body{{font-family:-apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo",sans-serif;
      margin:0;background:#f5f6f8;color:#222;line-height:1.5}}
 .wrap{{max-width:820px;margin:0 auto;padding:16px}}
 h1{{font-size:20px;margin:8px 0 2px}} .sub{{color:#777;font-size:13px;margin-bottom:14px}}
 .cards{{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}}
 .card{{flex:1 1 150px;background:#fff;border:1px solid #e6e8eb;border-radius:10px;padding:10px 12px}}
 .card .lbl{{font-size:12px;color:#888}} .card .val{{font-size:18px;font-weight:700;margin-top:2px}}
 .chart{{background:#fff;border:1px solid #e6e8eb;border-radius:10px;padding:10px;margin:10px 0}}
 h2{{font-size:15px;margin:18px 0 6px}}
 table{{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e6e8eb;border-radius:10px;overflow:hidden}}
 th,td{{text-align:left;padding:7px 9px;font-size:13px;border-bottom:1px solid #eef0f2;vertical-align:top}}
 th{{background:#fafbfc;color:#666;font-weight:600}}
 td.why{{color:#666;font-size:12px}}
 .note{{color:#999;font-size:12px;margin-top:16px}}
</style></head><body><div class="wrap">
 <h1>🤖 가상 포트폴리오 (AI 페이퍼 트레이딩)</h1>
 <div class="sub">시스템이 추천한 A등급 시그널을 확정 종가에 가상 매수해 동일 청산 엔진으로 굴린 <b>forward(실시간) 성적표</b> · 기간 {period} · 생성 {generated}</div>
 <div class="cards">{cards}</div>
 <div class="chart"><div class="lbl" style="font-size:12px;color:#888">자산 곡선 (시작 {s['start_equity']:,.0f})</div>{spark or '<div style="color:#999;font-size:13px;padding:20px 0">데이터 누적 중 — 청산이 2건 이상 쌓이면 곡선이 표시됩니다.</div>'}</div>

 <h2>보유 중 (가상)</h2>
 <table><tr><th>종목</th><th>등급</th><th>진입일</th><th>진입가→현재</th><th>평가손익</th></tr>
 {_open_rows(open_rows)}</table>

 <h2>최근 청산 (최대 20건)</h2>
 <table><tr><th>종목</th><th>등급</th><th>보유기간</th><th>일수</th><th>수익률</th><th>청산사유</th><th>매수근거</th></tr>
 {_trade_rows(trades)}</table>

 <h2>등급별 / 청산사유별</h2>
 <table><tr><th>등급</th><th>건수</th><th>성과</th></tr>{_breakdown_rows(stats.breakdown(trades, 'grade'))}</table>
 <div style="height:8px"></div>
 <table><tr><th>청산사유</th><th>건수</th><th>성과</th></tr>{_breakdown_rows(stats.breakdown(trades, 'exit_reason'))}</table>

 <div class="note">※ 실제 체결이 아닌 가상 매매입니다 ({cost_note}). 과거 성과가 미래 수익을 보장하지 않습니다.
 이 포트폴리오는 owner의 실제 보유와 무관합니다.</div>
</div></body></html>"""

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / PAPER_REPORT_NAME
    path.write_text(html_doc, encoding="utf-8")
    logger.info("paper dashboard written: %s", path)
    return path
