"""backtesting.py adapters reusing the LIVE strategy code path.

Entry signals are generated by calling each strategy's evaluate() on every
bar's prefix frame — the exact function the scanner runs — so scan and
backtest can never diverge (single source of truth, zero logic duplication).
Exits combine strategy.should_exit() with the shared exit engine.

Costs (always applied): slippage 0.1% per side; commission KR 0.015% per
side, US $0 — folded into backtesting.py's per-side commission rate.
"""

import logging
from dataclasses import dataclass

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy

from src.analysis.base_strategy import BaseStrategy
from src.risk import exit_engine

logger = logging.getLogger(__name__)

SLIPPAGE = 0.001  # 0.1% per side
COMMISSION = {"us": 0.0, "kr": 0.00015}  # per side
CASH = 1e9  # large enough for high-priced KRW tickers


@dataclass
class EntryPlan:
    """Precomputed per-bar entry decisions for one (ticker, strategy)."""

    entry: pd.Series  # bool per bar
    stop: pd.Series  # absolute stop level at entry bar (NaN when no entry)
    target: pd.Series  # absolute take-profit level (NaN = none)
    strength: pd.Series | None = None  # signal strength per entry bar (confluence)


def generate_entry_plan(
    df_ind: pd.DataFrame, strategy: BaseStrategy, ticker: str, market: str
) -> EntryPlan:
    """Run the live evaluate() over every bar prefix to build entry signals.

    Args:
        df_ind: compute_indicators() frame, full history, ascending dates.
        strategy: Strategy instance (YAML params bound).
        ticker: Ticker code.
        market: "us" | "kr".

    Returns:
        EntryPlan aligned to df_ind's index.
    """
    n = len(df_ind)
    entry = np.zeros(n, dtype=bool)
    stop = np.full(n, np.nan)
    target = np.full(n, np.nan)
    strength = np.full(n, np.nan)
    for i in range(strategy.min_bars, n):
        sig = strategy.evaluate(df_ind.iloc[: i + 1], ticker, ticker, market)
        if sig is not None:
            entry[i] = True
            stop[i] = sig.suggested_stop_loss if sig.suggested_stop_loss else np.nan
            target[i] = sig.suggested_take_profit if sig.suggested_take_profit else np.nan
            strength[i] = sig.strength
    return EntryPlan(
        entry=pd.Series(entry, index=df_ind.index),
        stop=pd.Series(stop, index=df_ind.index),
        target=pd.Series(target, index=df_ind.index),
        strength=pd.Series(strength, index=df_ind.index),
    )


def _bt_frame(df_ind: pd.DataFrame) -> pd.DataFrame:
    """Convert a canonical frame to backtesting.py's OHLCV format."""
    out = pd.DataFrame(
        {
            "Open": df_ind["open"].to_numpy(),
            "High": df_ind["high"].to_numpy(),
            "Low": df_ind["low"].to_numpy(),
            "Close": df_ind["close"].to_numpy(),
            "Volume": df_ind["volume"].to_numpy(),
        },
        index=pd.DatetimeIndex(pd.to_datetime(df_ind["date"])),
    )
    return out


def run_backtest(
    df_ind: pd.DataFrame,
    plan: EntryPlan,
    strategy: BaseStrategy,
    market: str,
) -> pd.DataFrame:
    """Simulate one (ticker, strategy) and return its trades.

    Args:
        df_ind: Indicator frame (full or sliced; plan must align).
        plan: generate_entry_plan() output aligned to df_ind.
        strategy: Strategy instance (exit params).
        market: "us" | "kr" (commission).

    Returns:
        Trades DataFrame: entry_time, exit_time, return_pct, holding_days.
        Empty frame when no trades.
    """
    if not plan.entry.any():
        return pd.DataFrame(columns=["entry_time", "exit_time", "return_pct", "holding_days"])

    entries = plan.entry.to_numpy()
    stops = plan.stop.to_numpy()
    targets = plan.target.to_numpy()
    frame = df_ind  # closed over by the adapter
    p = strategy.params
    time_stop = p.get("time_stop_days")
    atr_k = float(p.get("atr_k", 3.0))

    class Adapter(Strategy):
        """Generic adapter: precomputed entries + shared exit engine."""

        def init(self) -> None:
            self.entry_i: int | None = None
            self.entry_stop: float | None = None
            self.entry_target: float | None = None
            self.highest_close: float = 0.0

        def next(self) -> None:
            i = len(self.data) - 1
            close = float(self.data.Close[-1])
            if not self.position:
                if entries[i]:
                    self.buy()
                    self.entry_i = i
                    self.entry_stop = None if np.isnan(stops[i]) else float(stops[i])
                    self.entry_target = None if np.isnan(targets[i]) else float(targets[i])
                    self.highest_close = close
                return
            self.highest_close = max(self.highest_close, close)
            days_held = i - (self.entry_i or i)
            atr = frame["atr14"].iloc[i]
            state = exit_engine.PositionState(
                entry_price=float(self.trades[-1].entry_price),
                current_close=close,
                highest_close_since_entry=self.highest_close,
                days_held=days_held,
                atr=None if pd.isna(atr) else float(atr),
                stop_loss=self.entry_stop,
                take_profit=self.entry_target,
            )
            reason = None
            if state.atr is not None or strategy.exit_mode != "atr_trailing":
                reason = exit_engine.check_exit(
                    strategy.exit_mode, state, atr_k=atr_k, time_stop_days=time_stop
                )
            if reason is None:
                reason = strategy.should_exit(frame.iloc[: i + 1])
            if reason is not None:
                self.position.close()

    commission = SLIPPAGE + COMMISSION[market]
    bt = Backtest(
        _bt_frame(df_ind), Adapter, cash=CASH, commission=commission,
        exclusive_orders=True, finalize_trades=True,
    )
    stats = bt.run()
    trades = stats["_trades"]
    if trades.empty:
        return pd.DataFrame(columns=["entry_time", "exit_time", "return_pct", "holding_days"])
    return pd.DataFrame(
        {
            "entry_time": pd.to_datetime(trades["EntryTime"]),
            "exit_time": pd.to_datetime(trades["ExitTime"]),
            "return_pct": trades["ReturnPct"].astype(float),
            "holding_days": (trades["ExitBar"] - trades["EntryBar"]).astype(int),
        }
    )


def aggregate_stats(trades: pd.DataFrame) -> dict[str, float]:
    """Aggregate trade-level stats: n, win rate, profit factor, mean return.

    Profit factor = gross profit / gross loss across all trades.
    """
    if trades.empty:
        return {"n": 0, "win_rate": float("nan"), "profit_factor": float("nan"), "avg_return": float("nan")}
    r = trades["return_pct"]
    gross_profit = r[r > 0].sum()
    gross_loss = -r[r < 0].sum()
    pf = float("inf") if gross_loss == 0 and gross_profit > 0 else (
        float("nan") if gross_loss == 0 else gross_profit / gross_loss
    )
    return {
        "n": int(len(r)),
        "win_rate": float((r > 0).mean()),
        "profit_factor": float(pf),
        "avg_return": float(r.mean()),
        "avg_holding": float(trades["holding_days"].mean()),
    }
